name: Build and release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - ".github/workflows/build-and-release.yml"
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: write
  checks: write
  pull-requests: write
  packages: write

concurrency:
  group: build-and-release
  cancel-in-progress: true

jobs:
  build-and-release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: 1.22.1

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Build
      - name: Build
        shell: bash
        run: |
          set -x
          make ci
          echo "🎉 Builds completed" >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artefacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: gollama
          path: |
            gollama-*.zip

      # Bump version
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: dev

      # Bump latest version
      - name: Bump latest version
        id: tag_latest
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          custom_tag: latest

      # Publish
      - name: Create a GitHub release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
          allowUpdates: true
          prerelease: ${{ startsWith(github.ref, 'refs/heads/dev') }}
          draft: ${{ startsWith(github.ref, 'refs/heads/dev') }}
          artifacts: |
            gollama-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
